<a href="https://colab.research.google.com/github/chaitu1121/SAICHAITANYA_INFO5731_FALL2022/blob/main/In_class_exercise_03_10062022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (10/06/2022, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [36]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:
features used for building an machine learning model are
Number of sentences, Number of words, Number of characters, Number of stopwords, Lower casing, Punctuation removal
Not only these but there are so many features to build an machine learning model 





'''

'\nPlease write you answer here:\nfeatures used for building an machine learning model are\nNumber of sentences, Number of words, Number of characters, Number of stopwords, Lower casing, Punctuation removal\nNot only these but there are so many features to build an machine learning model \n\n\n\n\n\n'

Question 2 (20 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [37]:
# You code here (Please add comments in the code):
from six.moves import urllib
import pandas as pd
from urllib.request import urlopen


text = []
url = "https://raw.githubusercontent.com/chaitu1121/SAICHAITANYA_INFO5731_FALL2022/main/readme.txt"
x= urllib.request.urlopen(url)  

for i in x:
    dec_data = i.decode("utf-8").replace('\r\n', '')   
    if dec_data: 
        text.append(dec_data)       #appending the decoded data to a list
data = pd.DataFrame (text, columns = ['Text'])   #converting the list to data frame using pamdas
print(data)

                                                 Text
0   While stabilizing the original text of Ramayan...
1                                                  \n
2   However Book I, Balakanda is considered to be ...
3                                                  \n
4   Ramayana contains 24,000 verses [sloka] arrang...
5                                                  \n
6   This Valmiki Ramayana in Sanskrit is being tra...
7                                                  \n
8   We have started work on rendering Sanskrit ver...
9   Bala Kanda - Dr. (Mrs.) V. Roja Ravindra, Smt....
10  Kishkindha Kanda - Smt. Sujatha Srinivas Gopar...
11  Sundara Kanda - Smt. Aswini Ram Tulluri, Sri. ...
12  Audio mixing - Dr. V.S. Ravindra, Sri. V.S. Sa...
13                                                 \n
14  The verse below is recited at the beginning of...

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [39]:

# You code here (Please add comments in the code):
#to find num of sentences and words 

data['Num of sentences'] = data['Text'].apply(lambda y: len(str(y).split(".")))
data['Num of Words'] = data['Text'].apply(lambda y: len(str(y).split(" ")))
data['Num of Char'] = data['Text'].str.len()

data

,Text,Num of sentences,Num of Words,Num of Char
0,While stabilizing the original text of Ramayan...,13,117,709
1,\n,1,1,1
2,"However Book I, Balakanda is considered to be ...",5,99,610
3,\n,1,1,1
4,"Ramayana contains 24,000 verses [sloka] arrang...",7,113,741
5,\n,1,1,1
6,This Valmiki Ramayana in Sanskrit is being tra...,8,83,529
7,\n,1,1,1
8,We have started work on rendering Sanskrit ver...,4,25,158
9,"Bala Kanda - Dr. (Mrs.) V. Roja Ravindra, Smt....",5,12,73
10,Kishkindha Kanda - Smt. Sujatha Srinivas Gopar...,2,7,50
11,"Sundara Kanda - Smt. Aswini Ram Tulluri, Sri. ...",4,15,108
12,"Audio mixing - Dr. V.S. Ravindra, Sri. V.S. Sa...",7,9,54
13,\n,1,1,1
14,The verse below is recited at the beginning of...,1,12,65

In [40]:
def avg(x):
    jai = x.split() 
    if len(jai) != 0:  
        return(sum(len(deep) for deep in jai)/len(jai))
    else:
        return None

data['Avg Word Length'] = data['Text'].apply(lambda z: avg(z))
data

,Text,Num of sentences,Num of Words,Num of Char,Avg Word Length
0,While stabilizing the original text of Ramayan...,13,117,709,5.059829
1,\n,1,1,1,NaN
2,"However Book I, Balakanda is considered to be ...",5,99,610,5.214286
3,\n,1,1,1,NaN
4,"Ramayana contains 24,000 verses [sloka] arrang...",7,113,741,5.557522
5,\n,1,1,1,NaN
6,This Valmiki Ramayana in Sanskrit is being tra...,8,83,529,5.373494
7,\n,1,1,1,NaN
8,We have started work on rendering Sanskrit ver...,4,25,158,5.320000
9,"Bala Kanda - Dr. (Mrs.) V. Roja Ravindra, Smt....",5,12,73,5.083333
10,Kishkindha Kanda - Smt. Sujatha Srinivas Gopar...,2,7,50,6.142857
11,"Sundara Kanda - Smt. Aswini Ram Tulluri, Sri. ...",4,15,108,6.200000
12,"Audio mixing - Dr. V.S. Ravindra, Sri. V.S. Sa...",7,9,54,5.000000
13,\n,1,1,1,NaN
14,The verse below is recited at the beginning of...,1,12,65,4.416667

In [41]:
data.to_csv('data.csv',index=True)

In [42]:
'''most important features are
num of sentences

num of words
num of characters
average word length'''

'most important features are\nnum of sentences\n\nnum of words\nnum of characters\naverage word length'